### ISSUE TITLE
Router example is not popping routes with browser back button

### ISSUE THREAD

**Issue by wreppun** [orestesgaolin/navigator_20_example#5]
Hi, thanks for the examples.

I can't, however, get the router example to work properly.

If you navigate down through a few details pages, and then use the _browser_ back button to navigate back out, you'll notice that:

1. Pages are not popped off the stack.  Instead, duplicates are added to the stack.  If you go 1, 2, 3, 4, and hit the back button 4 times the stack ends up with 11 pages (via printing out `pageManager.pages.length`).  It appears to work because when you hit the home page, the logic dictates that all the pages are cleared.

2. onPopPage is never called.  I'm not sure if/how the browser back button is supposed to hook in here, but it doesn't.  So there is never a call to `pageManager.didPop(...)`

How are we supposed to handle the browser back button?

**Comment by wreppun** [comment]
This is probably why #4 happens too - if we use a `details.id` based key, hitting the back button creates a duplicate page.

**Comment by orestesgaolin** [comment]
Thanks for the issue!

From what I understand this is how it supposed to work i.e. by using browser back button you're not popping the page from the stack but going backwards in the history. You're right that the stacks shouldn't "stack" in such case. I will look into that tomorrow or as soon as possible. 

If you have any suggestions or potential fixes please let me know. The Router is still a bit mysterious for me even though I played with it for quite some time.

**Comment by wreppun** [comment]
Yeah, I'm definitely still puzzling through the navigator.  I couldn't even figure out how to tie to the browser back button.

I opened https://github.com/flutter/flutter/issues/71122.

**Comment by wreppun** [comment]
Based on the comments on that ticket, it looks like managing your own navigation stack for the web will not work.

There is no way to hook into the browser back button, and thus no way to keep the stack in sync if the user navigates via the browser controls.

Might consider adding a disclaimer to the `README`, since this is one of the few searchable examples of 2.0 out there.

**Comment by orestesgaolin** [comment]
> Might consider adding a disclaimer to the `README`, since this is one of the few searchable examples of 2.0 out there.

Thanks for that!

Can I use/rephrase what you've found out here in the README?

**Comment by wreppun** [comment]
Please do!

**Comment by wreppun** [comment]
After some follow up on that ticket, one step forward on implementation might be to:

1. Store the nav history in RoutePageManager, but external of Pages (maybe just the url, or using TheAppPath)
2. Store a single instance of each unique Page in `Navigator.pages` (maybe just one Main, one Unknown, and a Details for each one visited)
3. Reorder `Navigator.pages` when the the RoutePageManager state updates.

This does _not_ solve the issue of diverging histories (when using the browser nav vs the in-app nav), but at least you get an already-loaded page when you hit the back button in the browser.

**Comment by dleurs** [comment]
I have managed to solved part of this problem, please check the github example below<br/>

https://github.com/dleurs/flutter_navigator_2.0_demo_no_rebuild<br/>

First I am in :<br/>
1. /home (HomeScreen builds)
Press Todos<br/>
2. /home/todo (TodosScreen builds)
Press Todo 3<br/>
3. /home/todo/3 (TodoDetailsScreen of 3 builds)
I press navBar back button or web back button<br/>
4. /home/todo (**nothing rebuilds :D**)

It is a bit complicated, the idea is that I work a lot on keys.<br/>

However, I have not successfully managed to keep poped pages.<br/>

In the previous example, if i press back Todo 3<br/>
5. /home/todo/3 (TodoDetailsScreen of 3 builds again)

Even If i store this page in a _savedPage, and put it back in _pages when needed, it stills rebuild. (check branch no-rebuild-of-poped-widget)
